#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o phpstan
echo "";
echo "Aguarde, Rodando PHPStan... 😉";
echo "";
./vendor/bin/phpstan analyze --memory-limit=2G
if [ $? -ne 0 ]; then
    exit 1;
fi;

# rodar os testes
echo "Aguarde, Rodando testes... 😉";
echo "";
php artisan test --parallel
if [ $? -ne 0 ]; then
    exit 1;
fi;

# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;